name: "Nigiri Bitcoin"
description: "Run Nigiri Bitcoin in your Github Action"
inputs:
  version:
    description: "nigiri version to install"
    required: false
    default: "latest"
  repository_url:
    description: "Github repository URL of the repository with release artifacts"
    required: false
    default: "https://github.com/vulpemventures/nigiri"
  use_liquid:
    description: "use --liquid flag"
    required: false
    default: "true"
  use_ln:
    description: "use --ln flag"
    required: false
    default: "false"
  use_ark:
    description: "use --ark flag"
    required: false
    default: "false"
outputs: {}
runs:
  using: "node12"
  main: "index.js"
branding:
  icon: "box"
  color: "orange"
