name: "Nigiri Bitcoin"
description: "Run Nigiri Bitcoin in your Github Action"
inputs:
  version:
    description: "nigiri version to install"
    required: false
  repository_url:
    description: "Github repository URL of the repository with release artifacts"
    required: false
    default: "https://github.com/vulpemventures/nigiri"
outputs: {}
runs:
  using: "node12"
  main: "index.js"
branding:
  icon: "box"
  color: "orange"
